image: docker:latest

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: '$CI_REGISTRY/screamingbunny/webvalidator'

services:
  - name: docker:dind
    command:
      - /bin/sh
      - -c
      - |
          apk update && apk add openssl
          mkdir -p /etc/docker/certs.d/g2-inc.net
          wget -O - https://portal.g2-inc.com/sites/default/files/G2-Root-CA.pem > /etc/docker/certs.d/g2-inc.net/ca.crt || exit


stages:
  - build

before_script:
  - docker version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
   - docker build -t $IMAGE_NAME .
   - docker push $IMAGE_NAME