runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: lxml
  version: "3.7.3"

handlers:
- url: /static
  static_dir: webApp/static
  application_readable: true
- url: /.*
  script: webApp.app